#!/bin/bash

if [ $1 == 'none' ]; then
xrandr --output HDMI1 --off
elif [ $1 == 'right' ]; then
xrandr --output HDMI1 --auto --right-of LVDS1
elif [ $1 == 'left' ]; then
xrandr --output HDMI1 --auto --left-of LVDS1
fi
